import { Router } from "express";
import ThuongHieuController from "../controllers/ThuongHieuController.js";
import FlashSaleController from "../controllers/flashSaleController.js";
import SanPhamController from "../controllers/SanPhamController.js";
const websiteRoute = Router();
import multer from "multer";
const upload = multer();
websiteRoute.get('/laydsTH', upload.none(), ThuongHieuController.LayDanhSachThuongHieu);
websiteRoute.get('/laydsSPflashsale', upload.none(), FlashSaleController.LayDanhSachFlashSale);
websiteRoute.get('/thuonghieu_sanpham', upload.none(), ThuongHieuController.LaySanPhamTheoThuongHieu);
websiteRoute.get('/layChiTietSP_theoid', upload.none(), SanPhamController.layChiTietSP_theoid);
websiteRoute.get('/lay_ds_sanpham_moi', upload.none(), SanPhamController.layDanhSachSanPhamMoi);
websiteRoute.get('/sanpham_deal', upload.none(), SanPhamController.layDanhSachSanPhamDeal);
console.log("✅ websiteRoute loaded");
export default websiteRoute;